"""Integration test: compare vepyr annotation against Ensembl VEP golden standard.

Test data:
- input.vcf.gz: 100 variants from HG002 chr1, normalized with bcftools norm -m -both
- golden.vcf: matching Ensembl VEP 115 output with --everything flag
- reference.fa: trimmed GRCh38 chr1 (first ~860kb)
- cache/: trimmed parquet cache (generated by prepare.py, gitignored)
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

TESTS_DIR = Path(__file__).parent
GOLDEN_DIR = TESTS_DIR / "data" / "golden"
CACHE_DIR = str(GOLDEN_DIR / "cache")
INPUT_VCF = GOLDEN_DIR / "input.vcf.gz"
GOLDEN_VCF = GOLDEN_DIR / "golden.vcf"
REFERENCE_FASTA = GOLDEN_DIR / "reference.fa"


def _parse_golden_vcf(path: Path) -> dict[tuple[str, int, str, str], list[str]]:
    """Parse golden VCF into {(chrom, pos, ref, alt): [csq1, csq2, ...]}."""
    results = {}
    with open(path) as f:
        for line in f:
            if line.startswith("#"):
                continue
            fields = line.strip().split("\t")
            chrom, pos, _, ref, alt = fields[0], int(fields[1]), fields[2], fields[3], fields[4]
            info = fields[7]
            csq_entries = []
            for part in info.split(";"):
                if part.startswith("CSQ="):
                    csq_entries = part[4:].split(",")
                    break
            key = (chrom, pos, ref, alt)
            results[key] = csq_entries
    return results


def _extract_csq_field(csq: str, field_index: int) -> str:
    parts = csq.split("|")
    return parts[field_index] if field_index < len(parts) else ""


CSQ_CONSEQUENCE = 1
CSQ_IMPACT = 2
CSQ_SYMBOL = 3


def _normalize_chrom(chrom: str) -> str:
    return chrom.replace("chr", "")


@pytest.fixture(scope="module")
def golden_annotations():
    return _parse_golden_vcf(GOLDEN_VCF)


@pytest.fixture(scope="module")
def vepyr_df():
    if not os.path.isdir(CACHE_DIR):
        pytest.skip("Golden test cache not available")
    import vepyr
    return vepyr.annotate(
        str(INPUT_VCF), CACHE_DIR,
        everything=True, reference_fasta=str(REFERENCE_FASTA),
    ).collect()


class TestGoldenComparison:

    def test_variant_count(self, vepyr_df, golden_annotations):
        ratio = vepyr_df.height / len(golden_annotations)
        assert ratio >= 0.9, f"Too few: vepyr={vepyr_df.height}, golden={len(golden_annotations)}"

    def test_most_severe_consequence_match(self, vepyr_df, golden_annotations):
        matched = 0
        total = 0
        for row in vepyr_df.iter_rows(named=True):
            key = (row["chrom"], row["start"], row["ref"], row["alt"])
            norm_key = (_normalize_chrom(key[0]), key[1], key[2], key[3])
            golden_csqs = golden_annotations.get(key) or golden_annotations.get(norm_key)
            if golden_csqs is None:
                continue
            total += 1
            golden_consequences = {c for csq in golden_csqs for c in _extract_csq_field(csq, CSQ_CONSEQUENCE).split("&") if c}
            if row.get("most_severe_consequence") in golden_consequences:
                matched += 1
        assert total > 0
        assert matched / total >= 0.85, f"Match rate {matched/total:.1%} < 85%"

    def test_gene_symbol_match(self, vepyr_df, golden_annotations):
        matched = 0
        total = 0
        for row in vepyr_df.iter_rows(named=True):
            key = (row["chrom"], row["start"], row["ref"], row["alt"])
            norm_key = (_normalize_chrom(key[0]), key[1], key[2], key[3])
            golden_csqs = golden_annotations.get(key) or golden_annotations.get(norm_key)
            if golden_csqs is None:
                continue
            golden_symbols = {_extract_csq_field(csq, CSQ_SYMBOL) for csq in golden_csqs if _extract_csq_field(csq, CSQ_SYMBOL)}
            vepyr_symbol = row.get("SYMBOL", "")
            if not golden_symbols:
                continue
            total += 1
            if vepyr_symbol in golden_symbols:
                matched += 1
        assert total > 0
        assert matched / total >= 0.85, f"Gene symbol match {matched/total:.1%} < 85%"

    def test_impact_levels_present(self, vepyr_df):
        impacts = set(vepyr_df["IMPACT"].drop_nulls().to_list())
        expected = {"HIGH", "MODERATE", "LOW", "MODIFIER"}
        assert len(impacts & expected) >= 2, f"Expected >=2 IMPACT levels, got {impacts}"

    def test_hgvs_annotations_present(self, vepyr_df):
        hgvsc_count = vepyr_df["HGVSc"].drop_nulls().len()
        assert hgvsc_count > 0, "No HGVSc annotations with everything=True"

    def test_has_typed_columns(self, vepyr_df):
        expected = ["Consequence", "IMPACT", "SYMBOL", "Gene", "HGVSc", "HGVSp",
                     "SIFT", "PolyPhen", "AF", "gnomADe_AF", "gnomADg_AF"]
        for col in expected:
            assert col in vepyr_df.columns, f"Missing column: {col}"

    def test_column_count(self, vepyr_df):
        assert vepyr_df.width >= 90, f"Expected >=90 columns, got {vepyr_df.width}"
